# Generated by Django 6.0 on 2025-12-22 11:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueAttachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_url", models.URLField(max_length=1024)),
                ("file_type", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IssueCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "default_sla_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "author_type",
                    models.CharField(
                        choices=[("guest", "Guest"), ("staff", "Staff")],
                        max_length=16,
                    ),
                ),
                ("message", models.TextField()),
                ("is_internal", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="IssueStatusHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("old_status", models.CharField(max_length=32)),
                ("new_status", models.CharField(max_length=32)),
                (
                    "changed_by_type",
                    models.CharField(
                        choices=[("guest", "Guest"), ("staff", "Staff")],
                        max_length=16,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In progress"),
                            ("waiting_guest", "Waiting guest"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=32,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="normal",
                        max_length=16,
                    ),
                ),
                ("sla_due_at", models.DateTimeField(db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_guest_message_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_staff_response_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("guest_web", "Guest web"),
                            ("staff_app", "Staff app"),
                            ("import", "Import"),
                        ],
                        default="guest_web",
                        max_length=16,
                    ),
                ),
                (
                    "assigned_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_issues",
                        to="hotels.hoteldepartment",
                    ),
                ),
            ],
        ),
    ]
