# Generated by Django 6.0 on 2025-12-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0002_initial"),
        ("issues", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="assigned_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_issues",
                to="users.staffuser",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="guest_stay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="users.gueststay",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="hotels.hotel",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="hotels.room",
            ),
        ),
        migrations.AddField(
            model_name="issueattachment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issue_categories",
                to="hotels.hoteldepartment",
            ),
        ),
        migrations.AddField(
            model_name="issuecategory",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issue_categories",
                to="hotels.hotel",
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issues",
                to="issues.issuecategory",
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="author_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_comments",
                to="users.staffuser",
            ),
        ),
        migrations.AddField(
            model_name="issuecomment",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="issues.issue",
            ),
        ),
        migrations.AddField(
            model_name="issuestatushistory",
            name="changed_by_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_status_changes",
                to="users.staffuser",
            ),
        ),
        migrations.AddField(
            model_name="issuestatushistory",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="issues.issue",
            ),
        ),
        migrations.AddIndex(
            model_name="issuecategory",
            index=models.Index(
                fields=["hotel", "is_active"],
                name="issues_issu_hotel_i_e6f60e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["hotel", "status"],
                name="issues_issu_hotel_i_aa870b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["hotel", "created_at"],
                name="issues_issu_hotel_i_484b6d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuecomment",
            index=models.Index(
                fields=["issue", "created_at"],
                name="issues_issu_issue_i_51c69b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="issuestatushistory",
            index=models.Index(
                fields=["issue", "updated_at"],
                name="issues_issu_issue_i_1676bf_idx",
            ),
        ),
    ]
