# Generated by Django 6.0 on 2025-12-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hotels",
            "0004_remove_hoteldepartment_hotels_hote_hotel_i_e5c20c_idx_and_more",
        ),
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="issuecategory",
            name="issues_issu_hotel_i_e6f60e_idx",
        ),
        migrations.AddIndex(
            model_name="issuecategory",
            index=models.Index(
                fields=["name", "is_active"],
                name="issues_issu_name_98cb5f_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="issuecategory",
            name="hotel",
        ),
    ]
