# Generated by Django 6.0 on 2025-12-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotels", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoteluserrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hotel_roles",
                to="users.staffuser",
            ),
        ),
        migrations.AddField(
            model_name="hoteluserrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_roles",
                to="hotels.role",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hotels.hotel",
            ),
        ),
        migrations.AddIndex(
            model_name="hoteldepartment",
            index=models.Index(
                fields=["hotel", "code"], name="hotels_hote_hotel_i_e5c20c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hoteldepartment",
            unique_together={("hotel", "code")},
        ),
        migrations.AddIndex(
            model_name="hoteluserrole",
            index=models.Index(
                fields=["hotel", "user"], name="hotels_hote_hotel_i_74b176_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hoteluserrole",
            index=models.Index(
                fields=["hotel", "department"],
                name="hotels_hote_hotel_i_26b913_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["hotel", "number"],
                name="hotels_room_hotel_i_a7c4fc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(
                fields=("hotel", "number"), name="uniq_room_hotel_number"
            ),
        ),
    ]
