# Generated by Django 6.0 on 2025-12-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="id",
            field=models.AutoField(
                editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
