# Generated by Django 6.0 on 2025-12-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_alter_hotel_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hoteldepartment",
            name="hotels_hote_hotel_i_e5c20c_idx",
        ),
        migrations.AlterUniqueTogether(
            name="hoteldepartment",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="hoteldepartment",
            index=models.Index(
                fields=["code", "is_active"],
                name="hotels_hote_code_7a0ff6_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="hoteldepartment",
            name="hotel",
        ),
    ]
