# Generated by Django 6.0 on 2025-12-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "hotels",
            "0004_remove_hoteldepartment_hotels_hote_hotel_i_e5c20c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("department", "Department only"),
                    ("hotel", "Whole hotel"),
                    ("global", "All hotels"),
                ],
                default="department",
                max_length=16,
            ),
        ),
    ]
