# Generated by Django 6.0 on 2025-12-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.staffuser",
            ),
        ),
        migrations.AddField(
            model_name="usernotificationsettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to="users.staffuser",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["status", "created_at"],
                name="notificatio_status_68c9bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usernotificationsettings",
            index=models.Index(
                fields=["user", "channel_type", "is_active"],
                name="notificatio_user_id_54ad2a_idx",
            ),
        ),
    ]
